name: Deploy to Production Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: ${{ secrets.SHAKTI_BOT }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Directory Snapshot
      run: |
        mkdir snapshot
        rsync -av --exclude='.git' --exclude='.github' ./ snapshot/

    - name: Archive production artifacts
      run: |
        set -euxo pipefail
        tar -czvf packaged-code.tar.gz -C snapshot .
    - uses: actions/upload-artifact@v3
      with:
        name: packaged-code
        path: packaged-code.tar.gz

    - name: Send Telegram Notification on Archive Failure
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          🚨 [Бот][1/2] Архивирование не удалось! Пожалуйста, проверьте логи сборки.
          *️⃣ Подробности сборки можно посмотреть здесь: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

    - name: Send Telegram Notification on Archive Success
      if: success()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: "✅ [Бот][1/2] Архивирование успешно завершено!"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: packaged-code

    - name: Install lftp for SFTP
      run: sudo apt-get install lftp

    - name: SFTP Deploy
      run: |
        lftp -e "
        set ssl:verify-certificate no;
        set sftp:auto-confirm yes;
        open sftp://devilaks@devilaks.ftp.tools;
        user ${{ secrets.SFTP_USERNAME }} ${{ secrets.SFTP_PASSWORD }};
        lcd ./;
        cd /home/devilaks/bot;
        mirror --reverse --continue --verbose --parallel=10 . .;
        bye;
        "

    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        envs: BOT_TOKEN
        script: |
          echo "Exporting environment variables"
          export SHAKTI_BOT=${BOT_TOKEN}
          echo "Environment variables exported"
    
          echo "Changing directory to /home/devilaks/bot"
          cd /home/devilaks/bot
          echo "Current directory: $(pwd)"
    
          echo "Stopping the current bot process"
          ./stop.sh
          echo "Bot process stopped"
    
          echo "Checking for existing packaged-code.tar.gz file"
          if [ -f packaged-code.tar.gz ]; then
            echo "Found packaged-code.tar.gz. Proceeding to extract it"
          else
            echo "No packaged-code.tar.gz file found. Exiting script"
            exit 1
          fi
    
          echo "Extracting packaged-code.tar.gz"
          tar -xzvf packaged-code.tar.gz
          echo "Extraction complete"
    
          echo "Removing the extracted packaged-code.tar.gz file"
          rm --force packaged-code.tar.gz
          echo "packaged-code.tar.gz removed"
    
          echo "Starting the bot process"
          nohup ./run_bot.sh &
          echo "Bot process started"

    - name: Send Telegram Notification on Deploy Failure
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          🚨 [Бот][2/2] Развёртывание не удалось! Пожалуйста, проверьте логи сборки.
          *️⃣ Подробности сборки можно посмотреть здесь: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

    - name: Send Telegram Notification on Deploy Success
      if: success()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: "🚀 [Бот][2/2] Развёртывание успешно завершено! Проверьте бота: @anastasia_shakti_bot"
